### ISSUE TITLE
Not compatible with Python 3+ , Pl. start a development branch

### ISSUE THREAD

**Issue by srambhatla** [lisa-lab/DeepLearningTutorials#114]
The current version is not compatible with Python 3+ . A development branch, to initiate migration to Python 3, would be great. I will be happy to contribute. 
Thanks.

**Comment by nouiz** [comment]
I don't know anyone who will work on that shortly. So if you want to help
with that, it would be great.

thanks

On Sat, Aug 29, 2015 at 4:50 PM, Sirisha Rambhatla <notifications@github.com

**Comment by srambhatla** [comment]
Sure, will there be a development branch where I can contribute or do you want me to just fork the current version and send you a pull-request? 
Thanks.

**Comment by abergeron** [comment]
Pull request is the way to go.

**Comment by jli05** [comment]
How would you like it to be done? Would it be possible to simply port the code to Python 3.4+? (so it's no longer Python 2.7)

**Comment by nouiz** [comment]
We need to keep python 2.7 compatibility. In Theano, we do that by using
the six packages that give some compatibility layer between both version.

We also have some extension to this layer in theano/compat:

https://github.com/Theano/Theano/tree/master/theano/compat

If you can import what is needed from that, it would be good.

**Comment by Rahman29** [comment]
How to use cPickle in python 3.5. Should I need to shift to python 2.7? six.py doesn't work for me. Plz answer

**Comment by costapt** [comment]
By looking at Python's 3 porting guide (http://docs.pythonsprints.com/python3_porting/py-porting.html) you can simply import pickle instead of cPickle.

By doing that, Python chooses the C implementation if it is available, otherwise it falls back to the pure-Python version. I am not sure if you will have to change anything else, but the pickle itself should work.

**Comment by Rahman29** [comment]
I have tried that but unfortunately it creates other problems :-(

**Comment by costapt** [comment]
You can try this http://stackoverflow.com/questions/11305790/pickle-incompatability-of-numpy-arrays-between-python-2-and-3

I had that problem once and I think this solved it.

**Comment by Rahman29** [comment]
Thanks Pedro. Unfortunately it's not working at python 3.5. May be I need to check other versions as well.

Thanks again.

**Comment by nouiz** [comment]
We didn't port DLT to python 3. So if you fix one problem, you can hit
other after that. If you aren't ready to fix all of them, use Python 2.7.
If you fix some of them, making a PR with the fixes would be great.

**Comment by Rahman29** [comment]
Thanks Frédéric.

**Comment by Ogaday** [comment]
The [SO answer](http://stackoverflow.com/a/11314602/4244912) worked for me in Python 3 when loading the mnist dataset. If it doesn't work for you, I opened the data in python 2.7, concatenated all of the arrays, saved it in `.npy` format using `np.save`, then loaded it in python 3.5. Worked well too.

**Comment by nouiz** [comment]
Done in most part by gh-132. The missing part is outside code and we are working on this.

**Comment by gyom** [comment]
I now have a version of the midi module that works under python 2 and python 3. I have ran the thing for one epoch and checked that the midi files that produced are readable and not corrupted (the music sounds awful, though, but I'll run the thing for 200 epochs to make sure that it gets better).

I have put the zipped "midi" directory in /data/lisatmp2/alaingui/midi.zip, which should be readable by everyone. Since the zipped archive is not tracked by version control, I have nothing to check in along with this message.

It took me the whole day to track string formats versus bytes in python 2 and python 3, and what happened where. At the end of the day, the final approach was to observe the behavior of struct.pack under python 2 (returns a 'str') and python 3 (returns 'bytes'), and to mimic those types in the magic strings that are used as constants FILE_HEADER and TRACK_HEADER.

**Comment by lamblin** [comment]
We decided not to lose more time with the midi package for now.
Later, we can replace that tutorial with a similar one that would be python3-compatible.
