### ISSUE TITLE
Mulitprocessing performance of dA and SdA

### ISSUE THREAD

**Issue by benjaminirving** [lisa-lab/DeepLearningTutorials#140]
Hi, 

I was wondering if someone could explain the discrepancy between dA and SdA. 

Running test_dA() from dA.py results in all 12 cores on my computer being used at 100%, whereas running test_SdA() from SdA.py results in only a single core being used in the pretraining step of a single layer. 

This pretraining step trains using exactly the same dA class so I would expect performance to be the same. I can't find a reason why the one method uses multiprocessing and the other doesn't. 

Any ideas?

Thanks.

**Comment by nouiz** [comment]
I haven't checked that, but do you want to investigate a little? I don't
have time for this now.

First, is that on the CPU or GPU?
You can use Theano profile on both version and compare the output. if you
have difficulty understanding them, send them here, I can look at them
quickly.

http://deeplearning.net/software/theano/tutorial/profiling.html

Be sure to use Theano dev version. There have been many update since the
last release:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by benjaminirving** [comment]
Hi @nouiz , 

Thanks for the information. I'm using the dev bleeding edge version of Theano. I'm currently testing on the CPU. dA using 12 cores and SdA uses 1 core. 

I'm happy to investigate further and will look into profiling. Let me know if there is anything in dA.py that explicitly calls multiprocessing or openmp that may be disabled in the SdA.py version but otherwise I will see what I can find.

**Comment by nouiz** [comment]
There should be nothing in both version that would explicitly change th
parallelism on CPU.

**Comment by benjaminirving** [comment]
I've just found the reason. It's something small that I should have noticed. 

Default batch_size=1 on SdA, whereas batch_size=20 on dA

Therefore SdA just runs on a single core if run with test_SdA(). I would suggest updating the default batch_size=20 in SdA so that it's consistent with dA
