### ISSUE TITLE
Question about running logistic_cg.py

### ISSUE THREAD

**Issue by ErnstHowie** [lisa-lab/DeepLearningTutorials#73]
When I run the logistic_cg.py, I got these:

logistic_cg
... lThe code for file logistic_cg.py ran for 33.5s
The code for file mlp.py ran for 0.92m
The code for file convolutional_mlp.py ran for 0.82m
The no corruption code for file dA.py ran for 0.72m
The 30% corruption code for file dA.py ran for 0.73m
The pretraining code for file SdA.py ran for 1.84m
oading data
... building the model
Optimizing using scipy.optimize.fmin_cg...
validation error 29.989583 %
validation error 24.437500 %
validation error 20.760417 %
validation error 16.937500 %
validation error 14.270833 %
validation error 14.156250 %
validation error 13.177083 %
validation error 12.270833 %
validation error 11.697917 %
validation error 11.531250 %
validation error 10.531250 %
validation error 10.385417 %
validation error 10.135417 %
validation error 10.260417 %
validation error 9.885417 %
validation error 9.791667 %
validation error 9.208333 %
validation error 9.010417 %
validation error 8.937500 %
validation error 8.833333 %
validation error 8.760417 %
validation error 8.510417 %
validation error 8.354167 %
validation error 8.229167 %
validation error 8.270833 %
validation error 8.062500 %
validation error 7.979167 %
validation error 7.895833 %
validation error 7.875000 %
validation error 8.052083 %
Optimization complete with best validation score of 7.875000 %, with test performance 7.822917 %
The code run for 30 epochs in 0.559m, with 0.894673 epochs/sec

My question is that I don't know what these outputs mean:
"
... lThe code for file logistic_cg.py ran for 33.5s
The code for file mlp.py ran for 0.92m
The code for file convolutional_mlp.py ran for 0.82m
The no corruption code for file dA.py ran for 0.72m
The 30% corruption code for file dA.py ran for 0.73m
The pretraining code for file SdA.py ran for 1.84m
oading data
"
Is there something wrong with these output?

**Comment by lamblin** [comment]
On Sun, Feb 22, 2015, ErnstHowie wrote:
> My question is that I don't know what these outputs mean:
> "
> ... lThe code for file logistic_cg.py ran for 33.5s
> The code for file mlp.py ran for 0.92m
> The code for file convolutional_mlp.py ran for 0.82m
> The no corruption code for file dA.py ran for 0.72m
> The 30% corruption code for file dA.py ran for 0.73m
> The pretraining code for file SdA.py ran for 1.84m
> oading data
> "
> Is there something wrong with these output?

The fact that the running times get spliced in the middle of "loading"
is probably due to the fact that they are printed to stderr rather than
stdout.

However, I don't see why all the files would be mentioned in there,
and not only the current one.

-- 
Pascal

**Comment by ErnstHowie** [comment]
@lamblin It is very strange. I also don't know the reason. You said "the fact that they are printed to stderr rather than stdout". Do you mean there are some errors? Or my code is wrong?

**Comment by lamblin** [comment]
@ErnstHowie I'm just saying that "loading data" is printed to a stream called the standard output (stdout), while "The code for ..." is printed to a different stream called the standard error (stderr). Even if both are writing to the terminal, since stdout is buffered, the message printed on stderr can appear before the message in stdout is completely printed. This is not cause for concern.
Regarding the fact that all files are mentioned, did you modify the code at all? How are you launching the script? Is it possible that you are launching more than one script at once?

**Comment by ErnstHowie** [comment]
Okay. I understand what you mean. Thanks.
