### ISSUE TITLE
Add a "predict" function for logistic regression model

### ISSUE THREAD

**Issue by lamblin** [lisa-lab/DeepLearningTutorials#79]
It is a recurrent question, and has been suggested in https://groups.google.com/d/topic/theano-users/quGtLDGd_2Q/discussion

**Comment by memimo** [comment]
To fix this in a way that is not confusing for beginners we might need to change the current way tutorial is implemented. And don't define the graph inside the __init__ and have some fprop methods instead. If you guys are ok with this approach, I'll go ahead.

**Comment by nouiz** [comment]
Why do you need that? Can you just compile a function from with self.y_pred as output?

**Comment by memimo** [comment]
the reason is that currently the inputs to the theano function are passed to the __init__. After you pickle the model and reload and make a new thano function the inputs are not same anymore and theano compilation will raise an error. Whereas if it's defined inside fprop then you can pass new x, y even after reloading.
